PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../../..

# no target needed ... all *.h files will be included by default

# no package name prefix ... this will result in a l4/fmt/... header
INSTALL_INC_PREFIX = l4

include $(L4DIR)/mk/include.mk