PKGDIR  ?= ..
L4DIR   ?= $(PKGDIR)/../../..

TARGET   = function1 function2 function3

SRC_CC_function1 = function1.cc
SRC_CC_function2 = function2.cc
SRC_CC_function3 = function3.cc

REQUIRES_LIBS = libfaas

include $(L4DIR)/mk/prog.mk