PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../../..

TARGET   = liballoc.a
PC_FILENAME  = liballoc
SRC_CC   = $(patsubst $(SRC_DIR)/%,%,$(wildcard $(SRC_DIR)/*.cc))

# REQUIRES_LIBS = libstdc++ libfmt

include $(L4DIR)/mk/lib.mk