PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../../..

# Variables needed for the test environment
REQUIRES_LIBS += libgtest libfmt
NED_CFG       := test.cfg
REQUIRED_MODULES := mett-eagle example-function
TEST_GROUP    := mett-eagle

# surpress compile warnings
WARNINGS =

include $(L4DIR)/mk/test.mk